google:
  maps_api_key: ${{ secrets.GOOGLE_API_KEY }}
test:
  maps_api_key: ''
baidu:
  maps_api_key: ${{ secrets.BAIDU_API_KEY }}
address_provider: "google"

cache:
  redis:
    host: "localhost:6379"
    password: ""
    db: 0
  cache_db: "redis"

country: "AU"
port: 3000