google:
  maps_api_key: "${GOOGLE_MAPS_API_KEY}"
test:
  maps_api_key: ''
baidu:
  maps_api_key: "${BAIDU_MAPS_API_KEY}"
address_provider: "google"

cache:
  redis:
    host: "localhost:6379"
    password: ""
    db: 0
  cache_db: "redis"

country: "AU"
port: 3000