google:
  maps_api_key: 'AIzaSyBgvga-AvZjDZS64lttwWRVGcTnjUf0LiY'
test:
  maps_api_key: ''
baidu:
  maps_api_key: "${BITBUCKET_PR_DESTINATION_BRANCH}"
address_provider: "google"

cache:
  redis:
    host: "localhost:6379"
    password: ""
    db: 0
  cache_db: "redis"

country: "AU"
port: 3000