google:
  maps_api_key: ${{ secrets.GOOGLE_API_KEY }}
test:
  maps_api_key: ''
geoscape:
  maps_api_key: ${{ secrets.GEOSCAPE_API_KEY }}
address_provider: "google"

cache:
  redis:
    host: "localhost:6379"
    password: ""
    db: 0
  in_memory:
  cache_db: "in_memory"

country: "AU"
port: 3000